/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: IainHeap (https://sketchfab.com/IainHeap)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/e7f0a34a36f14c9292557673da4375fe
title: Broom Stick
*/


import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Canvas, useFrame } from '@react-three/fiber'
import { Suspense } from 'react/cjs/react.production.min'
import { OrbitControls } from '@react-three/drei'

//useFrame rotates the broom automatically
//scale is the image size

const BroomImageSettings = ({ ...props }) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/pictures/cherryBroomSticks/cherryBirch.glb')
  useFrame(() => {
    group.current.rotation.y -= 0.01
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.MainStick.geometry}
        material={materials['lambert2.001']}
        rotation={[Math.PI / 2, 0, 5]}
        scale={0.25}
      />
    </group>
  )
}

export const CherryBirchBroom = () => {
  return (
    <Canvas>
      <OrbitControls />
      <directionalLight intensity={0.5} />
      <ambientLight intensity={0.5} />
      <Suspense fallback={null}>
        <BroomImageSettings />
      </Suspense>
    </Canvas>
  )

}


useGLTF.preload('/pictures/cherryBroomSticks/cherryBirch.glb')